### ISSUE TITLE
pip download URL down

### ISSUE THREAD

**Issue by heyalexej** [jart/fabulous#7]
The package was hosted on http://lobstertech.com, which now is down since a while. There are things like [epub](https://github.com/rupa/epub) who depend on it in their requirements.txt. Could you please host it on Github? If you need help in maintaining the package etc.. please let me know.

**Comment by stuaxo** [comment]
Hi  @jart any chance of updating the version pypi ?

**Comment by jart** [comment]
There's one problem with that. I don't have access to the PyPi account anymore. It's tied to the LobsterTech domain so I can't reset the password. My attempt to reach out to the PyPi people failed last time I tried. I can give it another go if you guys like?

**Comment by stuaxo** [comment]
That would be awesome, I've found them helpful in the past - though probably like everything in open source, they are probably understaffed.

**Comment by jart** [comment]
Sigh they have absolutely no contact information. I'm going to try tweeting at people until someone helps me.

**Comment by stuaxo** [comment]
Will try some myself, hopefully different ones.

**Comment by stuaxo** [comment]
Worst comes to the worst could make fabulous2 and upload to pypi - but it would be un-ideal.

**Comment by jart** [comment]
It would be unfortunate if we had to fork the PyPi repo. So it'd be really good if we could find a way to get in touch with the guys running that service.

If you're truly motivated to breathe new life into this project, I'd be willing to consider granting you the necessary permissions to be its new maintainer. Is this something you would seriously consider? Because if you're serious, I'll be happy to put the time and effort into reviewing your work history to make sure the project will be going into capable hands, which I'm sure you have.

**Comment by stuaxo** [comment]
I found this library while looking at ANSI libraries for a work project, and the image display parts look really nice.

Given my previous record, I tend to be a bit of a fly-by developer - in that I'll come in and sort things, out then come back again in about a year, so not necessarily great as a maintainer.

I am interested in colour terminal stuff since the days DOS, so won't rule it out - I'd just like to use the project a bit first before volunteering for this.

You're right - forking the project on pypi would be unfortunate, I'll see keep seeing if I can find anyone who has something to do with pypi.

**Comment by r1chardj0n3s** [comment]
Hi, is there a support ticket on pypi (via the support link on the pypi site) related to the lost login?

**Comment by jart** [comment]
I had no idea a support page existed. Ticket filed! https://sourceforge.net/p/pypi/support-requests/627/

**Comment by jart** [comment]
Cool the password is reset! I can now update this. I'll probably do it in the next few days.

**Comment by stuaxo** [comment]
Thanks @r1chardj0n3s, I guess randomly pinging people on twitter eventually works - I guess, I should go open a ticket to add a more prominent link to the support page now :)

**Comment by jart** [comment]
Thank you for your patience everyone. I've fixed the download link for 0.1.5 on PyPi. I've also published a new release: 0.1.6. This project is now in a much healthier state. Since I've refreshed my memory on how everything works, I'm committed to being more active in my maintenance of this project in the future.
- https://github.com/jart/fabulous/releases
- https://pypi.python.org/pypi/fabulous/0.1.6
- https://pypi.python.org/pypi/fabulous/0.1.5

**Comment by jart** [comment]
Ok I tested things more thoroughly and had to bundle the grapefruit dependency. Now Fabulous will work 100% for sure from pip and easy_install. Although you have to use the [0.1.7](https://github.com/jart/fabulous/releases/tag/0.1.7) release. Old releases probably won't work.

Please also bear in mind that some distros have packaged Fabulous for years, e.g. [Debian / Ubuntu](https://packages.debian.org/jessie/python-fabulous) and [Red Hat / Fedora](http://rpm.pbone.net/index.php3/stat/3/srodzaj/1/search/python-fabulous).

**Comment by jart** [comment]
I also set up a GitHub pages website for Fabulous! https://jart.github.io/fabulous/

**Comment by stuaxo** [comment]
Great :) fantastic work, updating this and making it accessible for the future.
